services:
  # --- Object Storage (S3 Mock) ---
  minio:
    image: minio/minio:latest
    container_name: togo_minio
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Console (UI)
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - pipeline_net
  
  # --- Source: NoSQL Layer ---
  mongodb:
    image: mongo:8.2.5
    container_name: togo_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - pipeline_net

  # --- Processing: Spark Master ---
  spark-master:
    build: .
    env_file:
      - .env
    container_name: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./data:/app/data
    environment:
      - PYSPARK_PYTHON=python3
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - pipeline_net

  # --- Processing: Spark Worker ---
  spark-worker:
    build: .
    env_file:
      - .env
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    volumes:
      - ./src:/app/src
      - ./config:/app/config
      - ./data:/app/data
    depends_on:
      - spark-master
    networks:
      - pipeline_net

networks:
  pipeline_net:
    driver: bridge

volumes:
  minio_data: